#pragma once
#include "IntTypes.h"

enum class GameAction : uint8
{
	MOVE_LEFT,
	MOVE_RIGHT,
	AIM_UP,
	DOWN,
	AIM_DIAGONAL_UP,
	AIM_DIAGONAL_DOWN,
	JUMP,
	PRIMARY_ATTACK,
	SECONDARY_ATTACK,
	SELECT,
	SELECT_CANCEL,
	PAUSE,
	MENU_ACCEPT,
	MENU_CANCEL,

	DEBUG_LOG_SDL_ERROR,
	DEBUG_RESTART_MUSIC,
	DEBUG_ENABLE_FRAME_ADVANCE,
	DEBUG_ADVANCE_FRAME,
	ActionsCount,
};